import './globals.css'
import { Inter,Lalezar } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import ThemeProvider from './context/Theme'
const inter = Inter({ subsets: ['latin'] })
const lalezar=Lalezar({subsets:['arabic'],
weight:['400']})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <div className="container">
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </ThemeProvider>
       
        </body>
    </html>
  )
}
